# Logic
DEFAULT_TIMEZONE = "America/Chicago"

# Key to use when accessing flask app config
DATABASE_CONFIG_KEY = "DB"
BEERS_DATABASE_CONFIG_KEY = "BEER_DB"
DISKS_DATABASE_CONFIG_KEY = "DISKS_DB"
BIRDS_DATABASE_CONFIG_KEY = "BIRDS_DB"
BOOKS_DATABASE_CONFIG_KEY = "BOOKS_DB"
R2_CLIENT_CONFIG_KEY = "R2_CLIENT"

# Upload limits
MAX_COVER_IMAGE_SIZE_BYTES = 10 * 1024 * 1024  # 10 MB

# Cache
DATE_FORMAT_STRING = "%Y-%m-%d"
DATETIME_FORMAT_STRING = "%Y-%m-%dT%H:%M:%S"

ONE_HOUR_IN_SECONDS = 60 * 60
ONE_DAY_IN_SECONDS = 24 * 60 * 60

SESSION_LIFETIME_DAYS = 30

# Cloudflare CDN cache purge
CLOUDFLARE_API_TOKEN = "CLOUDFLARE_API_TOKEN"
CLOUDFLARE_ZONE_ID = "CLOUDFLARE_ZONE_ID"
