from datetime import timedelta

DATABASE_CONFIG_KEY = "db_config_key"

DB_NAME = "untappd"
BEERS_COLLECTION_NAME = "beers"
BEERS_ROWDY_COLLECTION_NAME = "beers_rowdy"
BREWERIES_COLLECTION_NAME = "breweries"
BEER_CACHE_TTL = timedelta(hours=1)
ROWDY_USERNAME = "rowdy"

__RAW_COUNTRIES = {
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Central African Rep",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Congo {Democratic Rep}",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "England",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "Isle of Man",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar, {Burma}",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "Northern Ireland",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "St. Kitts and Nevis",
    "St. Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Scotland",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Wales",
    "Yemen",
    "Zambia",
    "Zimbabwe",
}
# Sort the countries by longest first so we don't pick "Ireland" for a brewery in "Northern Ireland"
COUNTRIES = sorted(list(__RAW_COUNTRIES), key=len, reverse=True)

STYLES = {
    "Altbier - Sticke",
    "Altbier - Traditional",
    "Australian Sparkling Ale",
    "Barleywine - American",
    "Barleywine - English",
    "Barleywine - Other",
    "Belgian Blonde",
    "Belgian Dubbel",
    "Belgian Enkel / Patersbier",
    "Belgian Quadrupel",
    "Belgian Strong Dark Ale",
    "Belgian Strong Golden Ale",
    "Belgian Tripel",
    "Bitter - Best",
    "Bitter - Extra Special / Strong (ESB)",
    "Bitter - Session / Ordinary",
    "Bière de Champagne / Bière Brut",
    "Black & Tan",
    "Blonde / Golden Ale - American",
    "Blonde / Golden Ale - English",
    "Blonde / Golden Ale - Other",
    "Bock - Doppelbock",
    "Bock - Eisbock",
    "Bock - Hell / Maibock / Lentebock",
    "Bock - Single / Traditional",
    "Bock - Weizenbock",
    "Bock - Weizendoppelbock",
    "Brett Beer",
    "Brown Ale - American",
    "Brown Ale - Belgian",
    "Brown Ale - English",
    "Brown Ale - Imperial / Double",
    "Brown Ale - Other",
    "California Common",
    "Chilli / Chile Beer",
    "Cider - Applewine",
    "Cider - Basque",
    "Cider - Dry",
    "Cider - Graff",
    "Cider - Herbed / Spiced / Hopped",
    "Cider - Ice",
    "Cider - Other Fruit",
    "Cider - Perry / Poiré",
    "Cider - Rosé",
    "Cider - Sweet",
    "Cider - Traditional / Apfelwein",
    "Corn Beer / Chicha de Jora",
    "Cream Ale",
    "Cream Ale - Imperial / Double",
    "Dark Ale",
    "Farmhouse Ale - Bière de Coupage",
    "Farmhouse Ale - Bière de Garde",
    "Farmhouse Ale - Bière de Mars",
    "Farmhouse Ale - Brett",
    "Farmhouse Ale - Grisette",
    "Farmhouse Ale - Kornøl",
    "Farmhouse Ale - Other",
    "Farmhouse Ale - Sahti",
    "Farmhouse Ale - Saison",
    "Festbier",
    "Flavored Malt Beverage",
    "Freeze-Distilled Beer",
    "Fruit Beer",
    "Gluten-Free",
    "Golden Ale - Ukrainian",
    "Grape Ale - Italian",
    "Grape Ale - Other",
    "Grodziskie / Grätzer",
    "Happoshu",
    "Hard Ginger Beer",
    "Hard Kombucha / Jun",
    "Hard Seltzer",
    "Historical Beer - Adambier",
    "Historical Beer - Berliner Braunbier",
    "Historical Beer - Broyhan",
    "Historical Beer - Burton Ale",
    "Historical Beer - Dampfbier",
    "Historical Beer - Gruit / Ancient Herbed Ale",
    "Historical Beer - Kentucky Common",
    "Historical Beer - Kottbusser",
    "Historical Beer - Kuit / Kuyt / Koyt",
    "Historical Beer - Lichtenhainer",
    "Historical Beer - Mumme",
    "Historical Beer - Other",
    "Historical Beer - Steinbier",
    "Historical Beer - Zoigl",
    "Honey Beer",
    "IPA - American",
    "IPA - Belgian",
    "IPA - Black / Cascadian Dark Ale",
    "IPA - Brett",
    "IPA - Brown",
    "IPA - Brut",
    "IPA - Cold",
    "IPA - English",
    "IPA - Farmhouse",
    "IPA - Fruited",
    "IPA - Imperial / Double",
    "IPA - Imperial / Double Black",
    "IPA - Imperial / Double Milkshake",
    "IPA - Imperial / Double New England / Hazy",
    "IPA - Milkshake",
    "IPA - New England / Hazy",
    "IPA - New Zealand",
    "IPA - Other",
    "IPA - Quadruple",
    "IPA - Red",
    "IPA - Rye",
    "IPA - Session",
    "IPA - Sour",
    "IPA - Triple",
    "IPA - Triple New England / Hazy",
    "IPA - White / Wheat",
    "Kellerbier / Zwickelbier",
    "Koji / Ginjo Beer",
    "Kvass",
    "Kölsch",
    "Lager - Amber / Red",
    "Lager - American",
    "Lager - American Amber / Red",
    "Lager - American Light",
    "Lager - American Pre-Prohibition",
    "Lager - Dark",
    "Lager - Dortmunder / Export",
    "Lager - Helles",
    "Lager - IPL (India Pale Lager)",
    "Lager - Japanese Rice",
    "Lager - Leichtbier",
    "Lager - Mexican",
    "Lager - Munich Dunkel",
    "Lager - Other",
    "Lager - Pale",
    "Lager - Polotmavé (Czech Amber)",
    "Lager - Rotbier",
    "Lager - Smoked",
    "Lager - Strong",
    "Lager - Světlé (Czech Pale)",
    "Lager - Tmavé (Czech Dark)",
    "Lager - Vienna",
    "Lager - Winter",
    "Lambic - Faro",
    "Lambic - Framboise",
    "Lambic - Fruit",
    "Lambic - Gueuze",
    "Lambic - Kriek",
    "Lambic - Other",
    "Lambic - Traditional",
    "Makgeolli",
    "Malt Beer",
    "Malt Liquor",
    "Mead - Acerglyn / Maple Wine",
    "Mead - Bochet",
    "Mead - Braggot",
    "Mead - Cyser",
    "Mead - Melomel",
    "Mead - Metheglin",
    "Mead - Other",
    "Mead - Pyment",
    "Mead - Session / Short",
    "Mead - Traditional",
    "Mild - Dark",
    "Mild - Light",
    "Mild - Other",
    "Märzen",
    "Non-Alcoholic - IPA",
    "Non-Alcoholic - Lager",
    "Non-Alcoholic - Other",
    "Non-Alcoholic - Pale Ale",
    "Non-Alcoholic - Porter / Stout",
    "Non-Alcoholic - Shandy / Radler",
    "Non-Alcoholic - Sour",
    "Non-Alcoholic - Wheat Beer",
    "Non-Alcoholic - Cider / Perry",
    "Non-Alcoholic - Mead",
    "Old / Stock Ale",
    "Pale Ale - American",
    "Pale Ale - Australian",
    "Pale Ale - Belgian",
    "Pale Ale - English",
    "Pale Ale - Fruited",
    "Pale Ale - Milkshake",
    "Pale Ale - New England / Hazy",
    "Pale Ale - New Zealand",
    "Pale Ale - Other",
    "Pale Ale - XPA (Extra Pale)",
    "Pilsner - Czech / Bohemian",
    "Pilsner - German",
    "Pilsner - Imperial / Double",
    "Pilsner - Italian",
    "Pilsner - New Zealand",
    "Pilsner - Other",
    "Porter - American",
    "Porter - Baltic",
    "Porter - Coffee",
    "Porter - English",
    "Porter - Imperial / Double",
    "Porter - Imperial / Double Baltic",
    "Porter - Imperial / Double Coffee",
    "Porter - Other",
    "Porter - Smoked",
    "Pumpkin / Yam Beer",
    "Rauchbier",
    "Red Ale - American Amber / Red",
    "Red Ale - Imperial / Double",
    "Red Ale - Irish",
    "Red Ale - Other",
    "Roggenbier",
    "Root Beer",
    "Rye Beer",
    "Rye Wine",
    "Schwarzbier",
    "Scotch Ale / Wee Heavy",
    "Scottish Ale",
    "Scottish Export Ale",
    "Shandy / Radler",
    "Smoked Beer",
    "Sorghum / Millet Beer",
    "Sour - Berliner Weisse",
    "Sour - Catharina",
    "Sour - Flanders Oud Bruin",
    "Sour - Flanders Red Ale",
    "Sour - Fruited",
    "Sour - Fruited Berliner Weisse",
    "Sour - Fruited Gose",
    "Sour - Other",
    "Sour - Other Gose",
    "Sour - Smoothie / Pastry",
    "Sour - Tomato / Vegetable Gose",
    "Sour - Traditional Gose",
    "Specialty Grain",
    "Spiced / Herbed Beer",
    "Stout - American",
    "Stout - Belgian",
    "Stout - Coffee",
    "Stout - English",
    "Stout - Foreign / Export",
    "Stout - Imperial / Double",
    "Stout - Imperial / Double Coffee",
    "Stout - Imperial / Double Milk",
    "Stout - Imperial / Double Oatmeal",
    "Stout - Imperial / Double Pastry",
    "Stout - Imperial / Double White / Golden",
    "Stout - Irish Dry",
    "Stout - Milk / Sweet",
    "Stout - Oatmeal",
    "Stout - Other",
    "Stout - Oyster",
    "Stout - Pastry",
    "Stout - Russian Imperial",
    "Stout - White / Golden",
    "Strong Ale - American",
    "Strong Ale - English",
    "Strong Ale - Other",
    "Table Beer",
    "Traditional Ale",
    "Wheat Beer - American Pale Wheat",
    "Wheat Beer - Dunkelweizen",
    "Wheat Beer - Fruited",
    "Wheat Beer - Hefeweizen",
    "Wheat Beer - Hefeweizen Light / Leicht",
    "Wheat Beer - Hopfenweisse",
    "Wheat Beer - Kristallweizen",
    "Wheat Beer - Other",
    "Wheat Beer - Wheat Wine",
    "Wheat Beer - Witbier / Blanche",
    "Wild Ale - American",
    "Wild Ale - Other",
    "Winter Ale",
    "Winter Warmer",
}
